spring:
  application:
    name: discovery-service
  zipkin:
    base-url: http://192.168.99.100:9411/
server:
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/