server:
  port: 5555

spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://192.168.99.100:9411/
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
            allowedHeaders: "*"
      routes:
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/{segment}/orders/{segment}
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
            - NeedAdminRoleFilter
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/{segment}/orders/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
            - NeedAuthenticationFilter
        - id: core-service
          uri: lb://core-service
          predicates:
            - Path=/core/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-core
            - JwtAuthFilter
        - id: cart-service
          uri: lb://cart-service
          predicates:
            - Path=/cart/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-cart
            - JwtAuthFilter
        - id: auth-service-account-subscribers
          uri: lb://auth-service
          predicates:
            - Path=/auth/{segment}/account/subscribers
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
            - NeedAdminRoleFilter
        - id: auth-service-account
          uri: lb://auth-service
          predicates:
            - Path=/auth/{segment}/account/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
            - NeedAuthenticationFilter
        - id: auth-service-account
          uri: lb://auth-service
          predicates:
            - Path=/auth/{segment}/registration/confirm-email
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
            - NeedAuthenticationFilter
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-auth
            - JwtAuthFilter
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**
          filters:
            - StripPrefix=1
            - PrefixPath=/market-analytics
            - JwtAuthFilter

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      fetchRegistry: false

jwt:
  secret: h4f8093h4f983yhrt9834hr0934hf0hf493g493gf438rh438th34g34g